apiVersion: v1
kind: ServiceAccount
metadata:
  name: model-service
  labels:
    app: model-service
  annotations:
    # GCP Workload Identity annotation for GCS access
    iam.gke.io/gcp-service-account: model-zoo@PROJECT_ID.iam.gserviceaccount.com